# Generated by Django 3.1.6 on 2021-03-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                
                ('fname', models.CharField(max_length=122)),
                ('lname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=150)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pin', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=122)),
                ('retypepass', models.CharField(max_length=122)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
