# Generated by Django 3.1.6 on 2021-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210305_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='add',
            field=models.CharField(max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.TextField(verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=122, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='register',
            name='fname',
            field=models.CharField(max_length=122, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='lname',
            field=models.CharField(max_length=122, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=122, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='register',
            name='pin',
            field=models.CharField(max_length=15, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='register',
            name='retypepass',
            field=models.CharField(max_length=122, verbose_name='Retype Password'),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.TextField(verbose_name='State'),
        ),
    ]
