# Generated by Django 3.1.6 on 2021-03-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='home/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_des', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_email', to='home.register')),
                ('fname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_fname', to='home.register')),
                ('lname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_lname', to='home.register')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_phone', to='home.register')),
            ],
        ),
    ]
