# Generated by Django 3.1.4 on 2021-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_artist_artist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist1',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=122, verbose_name='First Name')),
                ('lname', models.CharField(max_length=122, verbose_name='Last Name')),
                ('email', models.CharField(max_length=122, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('add', models.CharField(max_length=150, verbose_name='Address')),
                ('des', models.TextField()),
                ('city', models.TextField(verbose_name='City')),
                ('state', models.TextField(verbose_name='State')),
                ('pin', models.CharField(max_length=15, verbose_name='Pincode')),
                ('password', models.CharField(max_length=122, verbose_name='Password')),
                ('retypepass', models.CharField(max_length=122, verbose_name='Retype Password')),
                ('image', models.ImageField(default='', upload_to='C:\\proper_project\\djangoproj\\etuning\\static\\img')),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='retypepass',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='C:\\djangoproj\\etuning\\static\\img'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
