# Generated by Django 3.1.4 on 2021-04-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210413_0944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist1',
            new_name='Artist2',
        ),
    ]
