# Generated by Django 3.1.4 on 2021-04-13 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210413_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='id',
            field=models.AutoField(auto_created=True,primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
