# Generated by Django 3.1.4 on 2021-04-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_register_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist2',
            name='retypepass',
        ),
    ]
