# Generated by Django 3.1.4 on 2021-04-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210414_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='usertype',
            field=models.CharField(default='customer', max_length=150, verbose_name='User Type'),
        ),
    ]
