# Generated by Django 3.1.4 on 2021-04-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_register_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
