# Generated by Django 3.1.4 on 2021-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210417_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_des',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
