# Generated by Django 3.2 on 2021-04-27 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_product_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist2',
            name='add',
        ),
        migrations.RemoveField(
            model_name='artist2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='artist2',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='artist2',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='artist2',
            name='password',
        ),
        migrations.RemoveField(
            model_name='artist2',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='artist2',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='artist2',
            name='username',
        ),
        migrations.RemoveField(
            model_name='register',
            name='des',
        ),
        migrations.RemoveField(
            model_name='register',
            name='image',
        ),
        migrations.AddField(
            model_name='artist2',
            name='category',
            field=models.CharField(default='empty', max_length=50, verbose_name='Category'),
        ),
        #migrations.AddField(
         #   model_name='artist2',
          #  name='id',
           # field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            #preserve_default=False,
        #),
        migrations.AlterField(
            model_name='artist2',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.register'),
        ),
        migrations.AlterField(
            model_name='artist2',
            name='image',
            field=models.ImageField(upload_to='uploads/artist'),
        ),
    ]
