# Generated by Django 3.2 on 2021-04-27 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210427_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist2',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist2',
            name='image',
            field=models.ImageField(upload_to='artist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
