# Generated by Django 3.2 on 2021-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_cart_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='message',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
