# Generated by Django 3.2 on 2021-05-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_cart_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=122, verbose_name='First Name')),
                ('lname', models.CharField(max_length=122, verbose_name='Last Name')),
                ('email', models.CharField(max_length=122, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('add', models.CharField(max_length=150, verbose_name='Address')),
                ('image', models.ImageField(upload_to='product')),
                ('product_name', models.CharField(max_length=122)),
                ('product_des', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('product_price', models.IntegerField(default=0,null = True)),
                ('category', models.CharField(max_length=122)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
