# Generated by Django 3.2 on 2021-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
