# Generated by Django 3.2 on 2021-05-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_sell_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
