# Generated by Django 3.2 on 2021-05-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_sell_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='image',
            new_name='product_image',
        ),
    ]
